// const
export const CHANGE_COLLAPSED_SIDEBAR = 'CHANGE_COLLAPSED_DETAILS'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_FULLFILLED = 'LOGIN_FULLFILLED'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'
export const SELECT_ROW = 'SELECT_ROW'
